# This docker compose is setting up the full ZKMintlayer network, consisting of:
#
# - L1 (private reth) with explorer (blockscout)
# - a single postgres (with all the databases)
# - a ipfs node
# - L2 zkmintlayer chain, together with its explorer
# - hyperexplorer to merge L1, L2 all together.

# Ports (if a port is written in the form http://localhost:PORT, it means that it can be accessed from the other machine):

#  - hyperexplorer: 
#      - http://localhost:15000 - http
#  - L1 chain (reth): 
#      - 15045 - rpc
#  - L1 explorer
#      - http://localhost:15001 - http
#      - http://localhost:15002 - 
#      - http://localhost:15003 -

#  - L2 chain (zkmintlayer):
#      - http://localhost:15100 - http rpc
#      - http://localhost:15101 - ws rpc
#  - L2 explorer:  
#      - http://localhost:15005 - http
#      - 3020 - explorer api
#      - 15103 - explorer worker
#      - 15104 - explorer data-fetcher
#      - 15105 - explorer api metrics
#
# Database is on 15432
# pgAdmin to manage PostgreSQL DB is on 15430

# Besides, mintlayer rpc is on 13034/3034, change this in the zkmintlayer service if needed.

services:
  reth:
    restart: always
    image: "ghcr.io/paradigmxyz/reth:v0.2.0-beta.2"
    volumes:
      - type: bind
        source: ./reth_chaindata
        target: /chaindata

    command: node --dev --datadir /rethdata --http --http.corsdomain "*" --http.addr 0.0.0.0 --http.port 8545  --dev.block-time 300ms --chain /chaindata/reth_config
    environment:
      - RUST_LOG=warn
    ports:
      - 127.0.0.1:15045:8545

  # ipfs:
  #   image: ipfs/kubo:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ipfs_path:/data/ipfs
  #     - ipfs_fuse:/ipfs
  #     - ipns_fuse:/ipns
  #   environment:
  #     - IPFS_PATH=/data/ipfs
  #   ports:
  #     # Swarm listens on all interfaces, so is remotely reachable.
  #     - 15402:4001/tcp
  #     - 15402:4001/udp
  #     # The following ports only listen on the loopback interface, so are not remotely reachable by default.
  #     # If you want to override these or add more ports, see https://docs.docker.com/compose/extends/ .
  #     # API port, which includes admin operations, so you probably don't want this remotely accessible.
  #     - 15403:5001
  #     # HTTP Gateway
  #     - 15401:8080

  postgres:
    image: "postgres:14"
    # To create necessary databases for block explorer.
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c 'max_connections=200'
    ports:
      - 127.0.0.1:15432:5432
    environment:
      # We bind only to 127.0.0.1, so setting insecure password is acceptable here
      - POSTGRES_PASSWORD=notsecurepassword

  pgadmin4:
    image: dcagatay/pwless-pgadmin4:latest
    ports:
      - 127.0.0.1:15430:80
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: notsecurepassword
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    restart: unless-stopped

  # zkmintlayer
  proxy-relay:
    image: alpine/socat:latest
    network_mode: host
    command: TCP-LISTEN:13034,fork,bind=host.docker.internal TCP-CONNECT:127.0.0.1:13034
    extra_hosts:
      - host.docker.internal:host-gateway

  zkmintlayer:
    stdin_open: true
    tty: true
    image: matterlabs/local-node:${INSTANCE_TYPE:-zkmintlayer}
    healthcheck:
      test: curl --fail http://localhost:3071/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 200
      start_period: 30s
    environment:
      - DATABASE_PROVER_URL=postgresql://postgres:notsecurepassword@postgres:5432/prover_local
      - DATABASE_URL=postgresql://postgres:notsecurepassword@postgres:5432/zksync_local
      - ETH_CLIENT_WEB3_URL=http://reth:8545
      - LEGACY_BRIDGE_TESTING=1
      # - IPFS_API_URL=http://ipfs:5001
      - ML_RPC_URL=http://host.docker.internal:13034 # change to mainnet if needed
      - ML_BATCH_SIZE=10 # change if necessary
      - 4EVERLAND_API_KEY=5F2R8SK2EQNSNCHSRWIK # only for test
      - 4EVERLAND_SECRET_KEY=sCGfIdQZfis8YVCXnQP53SL8cPdRxyzjPLh1KYmF # only for test
      - 4EVERLAND_BUCKET_NAME=zkmintlayer # only for test 
    ports:
      - 15100:3050 # JSON RPC HTTP port
      - 15101:3051 # JSON RPC WS port
    depends_on:
      - reth
      - postgres
      - proxy-relay
    volumes:
      - shared_config:/etc/env/target
      - shared_tokens:/etc/tokens
    extra_hosts:
      - host.docker.internal:host-gateway

  # L2 explorer: data-fetcher
  data-fetcher-main:
    platform: linux/amd64
    image: "matterlabs/block-explorer-data-fetcher:latest"
    environment:
      - PORT=3040
      - LOG_LEVEL=verbose
      - BLOCKCHAIN_RPC_URL=http://zkmintlayer:3050
    ports:
      - 127.0.0.1:15104:3040
    restart: unless-stopped

  # L2 explorer: worker
  worker-main:
    platform: linux/amd64
    image: "matterlabs/block-explorer-worker:latest"
    environment:
      - PORT=3001
      - LOG_LEVEL=verbose
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=notsecurepassword
      - DATABASE_NAME=block-explorer
      - BLOCKCHAIN_RPC_URL=http://zkmintlayer:3050
      - DATA_FETCHER_URL=http://data-fetcher-main:3040
      - BATCHES_PROCESSING_POLLING_INTERVAL=1000
    ports:
      - 127.0.0.1:15103:3001
    restart: unless-stopped

  # L2 explorer: API
  api-main:
    platform: linux/amd64
    image: "matterlabs/block-explorer-api:latest"
    environment:
      - PORT=3020
      - METRICS_PORT=3005
      - LOG_LEVEL=verbose
      - DATABASE_URL=postgresql://postgres:notsecurepassword@postgres:5432/block-explorer
    ports:
      - 127.0.0.1:3020:3020 # This is super tricky thing, as the explorer app must depends on api server running on port 3020. Should change the explorer app to have a better solution.
      - 127.0.0.1:15105:3005
    depends_on:
      - worker-main
    restart: unless-stopped

  # L2 explorer: APP
  app:
    platform: linux/amd64
    image: "matterlabs/block-explorer-app:latest"
    environment:
      - NODE_ENV=development
    ports:
      - 15005:3010
    depends_on:
      - api-main
    restart: unless-stopped

  # L1 Blockscout explorer: redis
  redis-db:
    image: 'redis:alpine'
    command: redis-server

  # L1 Blockscout explorer: backend
  backend:
    depends_on:
      - postgres
      - redis-db
    image: blockscout/blockscout:latest
    restart: always
    stop_grace_period: 5m
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    env_file:
      - blockscout/common-blockscout.env
    links:
      - postgres:database
    environment:
      - ETHEREUM_JSONRPC_VARIANT=geth
      - DATABASE_URL=postgresql://postgres:notsecurepassword@postgres:5432/blockscout
      - ETHEREUM_JSONRPC_HTTP_URL=http://reth:8545
      - ETHEREUM_JSONRPC_TRACE_URL=http://reth:8545

  # L1 Blockscout explorer: frontend
  frontend:
    depends_on:
      - backend
    image: ghcr.io/blockscout/frontend:latest
    platform: linux/amd64
    restart: always
    env_file:
      - blockscout/common-frontend.env

  stats:
    depends_on:
      - backend
    image: ghcr.io/blockscout/stats:latest
    platform: linux/amd64
    restart: always
    env_file:
      - blockscout/common-stats.env
    environment:
      - STATS__DB_URL=postgresql://postgres:notsecurepassword@postgres:5432/blockscout_stats
      - STATS__BLOCKSCOUT_DB_URL=postgresql://postgres:notsecurepassword@postgres:5432/blockscout
      - STATS__CREATE_DATABASE=true
      - STATS__RUN_MIGRATIONS=true

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    image: nginx
    volumes:
      - "./blockscout/proxy:/etc/nginx/templates"
    environment:
      BACK_PROXY_PASS: http://backend:4000
      FRONT_PROXY_PASS: http://frontend:3000
    ports:
      - target: 80
        published: 15001
      - target: 8080
        published: 15002
      - target: 8081
        published: 15003

  sig-provider:
    image: ghcr.io/blockscout/sig-provider:latest
    platform: linux/amd64
    restart: always

  hyperexplorer:
    depends_on:
      zkmintlayer:
        condition: service_healthy
    image: ghcr.io/mm-zk/zksync_tools:latest
    ports:
      - 15000:5000
    volumes:
      - ./hyperexplorer.json:/app/operator/config.json

volumes:
  reth:
  shared_config:
  shared_tokens:
    # ipfs_path:
    # ipfs_fuse:
    # ipns_fuse:
